version: '3'

services:
  scylla-node1:
    image: scylladb/scylla:6.0
    container_name: scylla-node1
    volumes:
      - /var/lib/scylla1:/var/lib/scylla
    environment:
      - reactor-backend=epoll
      - developer-mode=0
    networks:
      scylla:

  scylla-node2:
    image: scylladb/scylla:6.0
    container_name: scylla-node2
    volumes:
      - /var/lib/scylla2:/var/lib/scylla
    environment:
      - reactor-backend=epoll
      - develpoer-mode=0
    command: --seeds=scylla-node1
    networks:
      scylla:

  scylla-node3:
    image: scylladb/scylla:6.0
    container_name: scylla-node3
    volumes:
      - /var/lib/scylla3:/var/lib/scylla
    environment:
      - reactor-backend=epoll
      - developer-mode=0
    command: --seeds=scylla-node1
    networks:
      scylla:

networks:
  scylla:
    driver: bridge
    
